run:
  timeout: 5m
  tests: true

linters:
  disable:
    - typecheck  # Disable typecheck due to false positives with yaml imports
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
        - unused