local:
    enabled: true
    path: .tfstate_snapshots
    retention_count: 10
remote:
    provider: s3
    bucket: ""
    region: us-west-2
    prefix: ""
    enabled: false
encryption:
    provider: aes
    kms_key_id: ""
retention:
    local_count: 10
    remote_count: 50
    max_age_days: 90
logging:
    level: info
    format: text
